spring:
  datasource:
    //url: jdbc:postgresql://localhost:15432/postgres
    //username: postgres
    //password: secret
    //driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations:
      - classpath:/db/migration
server:
  port: 8081
doma:
  dialect: postgres
my.datasource.abstract:
  driverClassName: org.postgresql.Driver
datasource:
  data1:
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: secret
  data2:
    url: jdbc:postgresql://localhost:15433/postgres
    username: postgres
    password: secret